kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cfy-worker-log
  namespace: datadog
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: efs-sc
