---
apiVersion: v1
kind: Secret
type: opaque
metadata:
  name: s3-credentials
stringData:
  admin_access_key_id: ""
  admin_secret_access_key: ""
---
apiVersion: v1
kind: Secret
type: opaque
metadata:
  name: s3-session-token
stringData:
  session_token: ""
