apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: after-script
data:
  after_script.sh: |
    #!/usr/bin/env bash

    FILE=/mnt/cloudify-data/init-completed
    CLOUDIFY_DATA_DIR="/mnt/cloudify-data"

    if [ -f "$FILE" ]; then
      echo "Init flag exists!"
    else 
        cfy_manager stop

        echo "Copy necessary files to Persistent Volume"
        cp -a --verbose /etc/cloudify/config.yaml $CLOUDIFY_DATA_DIR
        cp -a --verbose /opt/mgmtworker/work/admin_token $CLOUDIFY_DATA_DIR
        cp -a --verbose /opt/manager/authorization.conf $CLOUDIFY_DATA_DIR
        cp -a --verbose /opt/manager/rest-security.conf $CLOUDIFY_DATA_DIR
        cp -a --verbose /opt/cloudify-composer/backend/conf/prod.json $CLOUDIFY_DATA_DIR
        cp -a --verbose /opt/cloudify-stage/conf/manager.json $CLOUDIFY_DATA_DIR

        echo "Copy necessary directories to Persistent Volume"
        cp -a --verbose /etc/cloudify/ssl $CLOUDIFY_DATA_DIR
        cp -a --verbose /opt/manager/resources $CLOUDIFY_DATA_DIR
        cp -a --verbose /opt/mgmtworker/env/plugins $CLOUDIFY_DATA_DIR
        cp -a --verbose /opt/cloudify-stage/dist/userData $CLOUDIFY_DATA_DIR
        
        touch "$CLOUDIFY_DATA_DIR/init-completed"

        echo "Removed unused directory"
        rm -rf --verbose /etc/cloudify/ssl
        rm -rf --verbose /opt/manager/resources
        rm -rf --verbose /opt/mgmtworker/env/plugins
        rm -rf --verbose /opt/cloudify-stage/dist/userData

        echo "Removed unused files"
        rm --verbose /opt/mgmtworker/work/admin_token
        rm --verbose /opt/manager/authorization.conf
        rm --verbose /opt/manager/rest-security.conf
        rm --verbose /opt/cloudify-composer/backend/conf/prod.json
        rm --verbose /opt/cloudify-stage/conf/manager.json

        echo "Making symbolic links for directory"
        ln -s --verbose "$CLOUDIFY_DATA_DIR/ssl" /etc/cloudify/ssl
        ln -s --verbose "$CLOUDIFY_DATA_DIR/resources" /opt/manager/resources
        ln -s --verbose "$CLOUDIFY_DATA_DIR/plugins" /opt/mgmtworker/env/plugins
        ln -s --verbose "$CLOUDIFY_DATA_DIR/userData" /opt/cloudify-stage/dist/userData

        echo "Making symbolic links for files"
        ln -s --verbose "$CLOUDIFY_DATA_DIR/admin_token" /opt/mgmtworker/work/admin_token
        ln -s --verbose "$CLOUDIFY_DATA_DIR/authorization.conf" /opt/manager/authorization.conf
        ln -s --verbose "$CLOUDIFY_DATA_DIR/rest-security.conf" /opt/manager/rest-security.conf
        ln -s --verbose "$CLOUDIFY_DATA_DIR/prod.json" /opt/cloudify-composer/backend/conf/prod.json
        ln -s --verbose "$CLOUDIFY_DATA_DIR/manager.json" /opt/cloudify-stage/conf/manager.json

        cfy_manager start
    fi
