apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: before-hook
data:
  before_hook.sh: |
    #!/usr/bin/env bash
    set -eux

    FILE=/mnt/{{ .Release.Namespace }}/init-completed
    CLOUDIFY_DATA_DIR="/mnt/{{ .Release.Namespace }}"
    
    mkdir -p /mnt/{{ .Release.Namespace }}/etc
    mkdir -p /mnt/{{ .Release.Namespace }}/manager
    mkdir -p /mnt/{{ .Release.Namespace }}/mgmtworker
    mkdir -p /mnt/{{ .Release.Namespace }}/cloudify-composer
    mkdir -p /mnt/{{ .Release.Namespace }}/cloudify-stage
    
    if [ -f "$FILE" ]; then
      echo "The Data exists on PV - creating symbolic links to files and folders on PV"
      rm -f /etc/cloudify/config.yaml
      cp -a --verbose "$CLOUDIFY_DATA_DIR/etc/config.yaml" /etc/cloudify/config.yaml

      echo "Remove unused directory"
      rm -rf --verbose /opt/manager/resources
      rm -rf --verbose /opt/mgmtworker/env/plugins
      rm -rf --verbose /opt/cloudify-stage/dist/userData

      echo "Remove unused files"
      rm -f --verbose /opt/mgmtworker/work/admin_token
      rm -f --verbose /opt/manager/authorization.conf
      rm -f --verbose /opt/manager/rest-security.conf
      rm -f --verbose /opt/cloudify-composer/backend/conf/prod.json
      rm -f --verbose /opt/cloudify-composer/backend/conf/db_ca.crt
      rm -f --verbose /opt/cloudify-stage/conf/db_ca.crt
      rm -f --verbose /opt/cloudify-stage/conf/manager.json
      
      echo "Making symbolic links for files"
      ln -s --verbose "$CLOUDIFY_DATA_DIR/mgmtworker/admin_token" /opt/mgmtworker/work/admin_token
      ln -s --verbose "$CLOUDIFY_DATA_DIR/manager/authorization.conf" /opt/manager/authorization.conf
      ln -s --verbose "$CLOUDIFY_DATA_DIR/manager/rest-security.conf" /opt/manager/rest-security.conf
      ln -s --verbose "$CLOUDIFY_DATA_DIR/cloudify-composer/prod.json" /opt/cloudify-composer/backend/conf/prod.json
      ln -s --verbose "$CLOUDIFY_DATA_DIR/cloudify-composer/db_ca.crt" /opt/cloudify-composer/backend/conf/db_ca.crt
      ln -s --verbose "$CLOUDIFY_DATA_DIR/cloudify-stage/db_ca.crt" /opt/cloudify-stage/conf/db_ca.crt
      ln -s --verbose "$CLOUDIFY_DATA_DIR/cloudify-stage/manager.json" /opt/cloudify-stage/conf/manager.json

      echo "Making symbolic links for directory"
      ln -s --verbose "$CLOUDIFY_DATA_DIR/manager/resources" /opt/manager/resources
      ln -s --verbose "$CLOUDIFY_DATA_DIR/mgmtworker/plugins" /opt/mgmtworker/env/plugins
      ln -s --verbose "$CLOUDIFY_DATA_DIR/cloudify-stage/userData" /opt/cloudify-stage/dist/userData
    else 
      echo "Copy config"
      rm -f /etc/cloudify/config.yaml
      cp /tmp/cloudify/config.yaml /etc/cloudify/config.yaml
      sudo chown cfyuser /etc/cloudify/config.yaml
    fi
