apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: before-hook
data:
  before_hook.sh: |
    #!/usr/bin/env bash

    FILE=/mnt/cloudify-data/init-completed
    CLOUDIFY_DATA_DIR="/mnt/cloudify-data"
    
    mkdir -p /etc/cloudify/ssl
    mkdir -p /mnt/cloudify-data/etc
    mkdir -p /mnt/cloudify-data/manager
    mkdir -p /mnt/cloudify-data/mgmtworker
    mkdir -p /mnt/cloudify-data/cloudify-composer
    mkdir -p /mnt/cloudify-data/cloudify-stage
    
    if [ -f "$FILE" ]; then
      echo "The Data exists on PV - creating symbolic links to files and folders on PV"
      rm -f /etc/cloudify/config.yaml
      cp -a --verbose "$CLOUDIFY_DATA_DIR/etc/config.yaml" /etc/cloudify/config.yaml

      echo "Removed unused directory"
      rm -rf --verbose /etc/cloudify/ssl
      rm -rf --verbose /opt/manager/resources
      rm -rf --verbose /opt/mgmtworker/env/plugins
      rm -rf --verbose /opt/cloudify-stage/dist/userData

      echo "Removed unused files"
      rm --verbose /opt/mgmtworker/work/admin_token
      rm --verbose /opt/manager/authorization.conf
      rm --verbose /opt/manager/rest-security.conf
      rm --verbose /opt/cloudify-composer/backend/conf/prod.json
      rm --verbose /opt/cloudify-composer/backend/conf/db_ca.crt
      rm --verbose /opt/cloudify-stage/conf/db_ca.crt
      rm --verbose /opt/cloudify-stage/conf/manager.json
      
      echo "Making symbolic links for files"
      ln -s --verbose "$CLOUDIFY_DATA_DIR/mgmtworker/admin_token" /opt/mgmtworker/work/admin_token
      ln -s --verbose "$CLOUDIFY_DATA_DIR/manager/authorization.conf" /opt/manager/authorization.conf
      ln -s --verbose "$CLOUDIFY_DATA_DIR/manager/rest-security.conf" /opt/manager/rest-security.conf
      ln -s --verbose "$CLOUDIFY_DATA_DIR/cloudify-composer/prod.json" /opt/cloudify-composer/backend/conf/prod.json
      ln -s --verbose "$CLOUDIFY_DATA_DIR/cloudify-composer/db_ca.crt" /opt/cloudify-composer/backend/conf/db_ca.crt
      ln -s --verbose "$CLOUDIFY_DATA_DIR/cloudify-stage/db_ca.crt" /opt/cloudify-stage/conf/db_ca.crt
      ln -s --verbose "$CLOUDIFY_DATA_DIR/cloudify-stage/manager.json" /opt/cloudify-stage/conf/manager.json

      echo "Making symbolic links for directory"
      ln -s --verbose "$CLOUDIFY_DATA_DIR/etc/ssl" /etc/cloudify/ssl
      ln -s --verbose "$CLOUDIFY_DATA_DIR/manager/resources" /opt/manager/resources
      ln -s --verbose "$CLOUDIFY_DATA_DIR/mgmtworker/plugins" /opt/mgmtworker/env/plugins
      ln -s --verbose "$CLOUDIFY_DATA_DIR/cloudify-stage/userData" /opt/cloudify-stage/dist/userData
    else 
      echo "Copy config"
      rm -f /etc/cloudify/config.yaml
      cp /tmp/cloudify/config.yaml /etc/cloudify/config.yaml
      sudo chown cfyuser /etc/cloudify/config.yaml
      
      echo "Copy certificates"
      cp /tmp/cloudify/one-key.pem /etc/cloudify/ssl/postgres-client-key.pem
      cp /tmp/cloudify/one-key.pem /etc/cloudify/ssl/key.pem
      cp /tmp/cloudify/one-key.pem /etc/cloudify/ssl/external-key.pem

      cp /tmp/cloudify/one-cert.pem /etc/cloudify/ssl/postgres-client-cert.pem
      cp /tmp/cloudify/ca-cert.pem /etc/cloudify/ssl/postgresql-ca-cert.pem
      cp /tmp/cloudify/ca-cert.pem /etc/cloudify/ssl/ca.pem
      cp /tmp/cloudify/one-cert.pem /etc/cloudify/ssl/cert.pem
      cp /tmp/cloudify/one-cert.pem /etc/cloudify/ssl/external-cert.pem

      cp /tmp/cloudify/ca-cert.pem /etc/cloudify/ssl/postgresql_ca.crt
      sudo chown cfyuser /etc/cloudify/ssl/postgresql_ca.crt

      cp /tmp/cloudify/ca-cert.pem /opt/cloudify-stage/conf/db_ca.crt
      sudo chown cfyuser /opt/cloudify-stage/conf/db_ca.crt

      cp /tmp/cloudify/ca-cert.pem /opt/cloudify-composer/backend/conf/db_ca.crt
      sudo chown cfyuser /opt/cloudify-composer/backend/conf/db_ca.crt
    fi
