apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: cfy-starter
data:
  cfy_starter.sh: |
    #!/usr/bin/env bash
    
    echo "Hello world and peace!"
    echo 'started' > /tmp/cfy_started_init.txt
