apiVersion: v1
kind: ConfigMap
metadata:
  name: cfy-starter
data:
  cfy_starter.sh: |
    #!/usr/bin/env bash
    
    echo 'Start delay'
    sleep {{ .Values.config.startDelay }}

    BEFORE_HOOK=/tmp/before_hook_completed
    AFTER_HOOK=/tmp/after_hook_completed

    if [ -f "$BEFORE_HOOK" ]; then
      echo 'before_hook already executed!'
    else 
      sh /tmp/cloudify/before_hook.sh
      touch /tmp/before_hook_completed
    fi

    {{ if (.Values.hotfix).rnd1267 }}
    sed -ie 's|if os.path.ismount(path)|if os.path.isdir(path) and os.path.ismount(path)|' /opt/cloudify/cfy_manager/lib/python3.11/site-packages/cfy_manager/utils/files.py
    {{ end }}
    echo 'Run cloudify manager'
    /usr/bin/cfy_manager image-starter

    if [ -f "$AFTER_HOOK" ]; then
      echo 'after_hook already executed!'
    else 
      sh /tmp/cloudify/after_hook.sh
      touch /tmp/after_hook_completed
    fi

    {{ .Values.config.after_bash }}
    
