apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: cloudify-config
data:
  config.yaml: |
    manager:
      private_ip: {{ .Values.service.host }}
      public_ip: {{ .Values.service.host }}
      hostname: {{ .Values.service.host }}
      cli_local_profile_host_name: {{ .Values.service.host }}
      security:
        ssl_enabled: true
        admin_password: admin

    rabbitmq:
      username: {{ .Values.queue.username }}
      password: {{ .Values.queue.password }}
      ca_path: '/mnt/cloudify-data/ssl/ca.crt'
      cert_path: '/mnt/cloudify-data/ssl/tls.crt'
      key_path: '/mnt/cloudify-data/ssl/tls.key'
      cluster_members:
        rabbit1:
          networks:
            default: {{ .Values.queue.host }}

    postgresql_client:
      host: {{ .Values.db.host }}
      server_db_name: {{ .Values.db.server_db_name }}
      server_username: {{ .Values.db.server_username }}
      server_password: {{ .Values.db.server_password }}
      cloudify_db_name: {{ .Values.db.cloudify_db_name }}
      cloudify_username: {{ .Values.db.cloudify_username }}
      cloudify_password: {{ .Values.db.cloudify_password }}
      ca_path: '/mnt/cloudify-data/ssl/ca.crt'
      ssl_enabled: true
      ssl_client_verification: true
    postgresql_server:
      postgres_password: {{ .Values.db.server_password }}
      ca_path: '/mnt/cloudify-data/ssl/ca.crt'
      cert_path: '/mnt/cloudify-data/ssl/tls.crt'
      key_path: '/mnt/cloudify-data/ssl/tls.key'

    prometheus:
      ca_path: '/mnt/cloudify-data/ssl/ca.crt'
      cert_path: '/mnt/cloudify-data/ssl/tls.crt'
      key_path: '/mnt/cloudify-data/ssl/tls.key'
      scrape_interval: 5s

    ssl_inputs:
      postgresql_client_cert_path: /mnt/cloudify-data/ssl/tls.crt
      postgresql_client_key_path: /mnt/cloudify-data/ssl/tls.key
      postgresql_ca_cert_path: /mnt/cloudify-data/ssl/ca.crt
      ca_cert_path: /mnt/cloudify-data/ssl/ca.crt
      internal_cert_path: /mnt/cloudify-data/ssl/tls.crt
      internal_key_path: /mnt/cloudify-data/ssl/tls.key
      external_cert_path: /mnt/cloudify-data/ssl/tls.crt
      external_key_path: /mnt/cloudify-data/ssl/tls.key
      external_ca_cert_path: /mnt/cloudify-data/ssl/ca.crt

    validations:
      skip_validations: true

    services_to_install:
    - manager_service
    - monitoring_service

    service_management: supervisord