apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: cloudify-config
data:
  config.yaml: |
    manager:
      private_ip: {{ .Values.service.host }}.{{.Values.domain}}
      public_ip: {{ .Values.service.host }}.{{.Values.domain}}
      hostname: {{ .Values.service.host }}.{{.Values.domain}}
      cli_local_profile_host_name: {{ .Values.config.cli_local_profile_host_name }}
      security:
        ssl_enabled: {{ .Values.config.security.ssl_enabled }}
        admin_password: {{ .Values.config.security.admin_password }}
      {{- if .Values.licence }}
      cloudify_license_path: /tmp/cloudify/cfy_licence.yaml
      {{- end}}

    rabbitmq:
      username: {{ .Values.queue.username }}
      password: {{ .Values.queue.password }}
      ca_path: {{ .Values.config.ca_cert_path }}
      cert_path: {{ .Values.config.tls_cert_path }}
      key_path: {{ .Values.config.tls_key_path }}
      is_external: true
      cluster_members:
        rabbit1:
          networks:
            default: {{ .Values.queue.host }}.{{.Values.domain}}

    postgresql_client:
      host: {{ .Values.db.host }}.{{ .Values.domain }}
      server_db_name: {{ .Values.db.server_db_name }}
      server_username: {{ .Values.db.server_username }}
      server_password: {{ .Values.db.server_password }}
      cloudify_db_name: {{ .Values.db.cloudify_db_name }}
      cloudify_username: {{ .Values.db.cloudify_username }}
      cloudify_password: {{ .Values.db.cloudify_password }}
      ca_path: {{ .Values.config.ca_cert_path }}
      ssl_enabled: true
      ssl_client_verification: true
    postgresql_server:
      postgres_password: {{ .Values.db.server_password }}
      ca_path: {{ .Values.config.ca_cert_path }}
      cert_path: {{ .Values.config.tls_cert_path }}
      key_path: {{ .Values.config.tls_key_path }}

    prometheus:
      ca_path: {{ .Values.config.ca_cert_path }}
      cert_path: {{ .Values.config.tls_cert_path }}
      key_path: {{ .Values.config.tls_key_path }}
      scrape_interval: 5s

    ssl_inputs:
      postgresql_client_cert_path: {{ .Values.config.tls_cert_path }}
      postgresql_client_key_path: {{ .Values.config.tls_key_path }}
      postgresql_ca_cert_path: {{ .Values.config.ca_cert_path }}
      ca_cert_path: {{ .Values.config.ca_cert_path }}
      internal_cert_path: {{ .Values.config.tls_cert_path }}
      internal_key_path: {{ .Values.config.tls_key_path }}
      external_cert_path: {{ .Values.config.tls_cert_path }}
      external_key_path: {{ .Values.config.tls_key_path }}
      external_ca_cert_path: {{ .Values.config.ca_cert_path }}

    validations:
      skip_validations: true
    
    sanity:
      skip_sanity: true

    services_to_install:
    - manager_service
    - monitoring_service

    service_management: supervisord