apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: cloudify-config
data:
  config.yaml: |
    manager:
      private_ip: {{ .Values.service.host }}
      public_ip: {{ .Valueblus.service.host }}
      hostname: {{ .Values.service.host }}
      cli_local_profile_host_name: {{ .Values.service.host }}
      security:
        ssl_enabled: true
        admin_password: admin

    rabbitmq:
      username: {{ .Values.queue.username }}
      password: {{ .Values.queue.password }}
      ca_path: '/etc/cloudify/ca.pem'
      cert_path: '/etc/cloudify/external-cert.pem'
      key_path: '/etc/cloudify/external-key.pem'
      cluster_members:
        rabbit1:
          networks:
            default: {{ .Values.queue.host }}

    postgresql_client:
      host: {{ .Values.db.host }}
      server_db_name: {{ .Values.db.server_db_name }}
      server_username: {{ .Values.db.server_username }}
      server_password: {{ .Values.db.server_password }}
      cloudify_db_name: {{ .Values.db.cloudify_db_name }}
      cloudify_username: {{ .Values.db.cloudify_username }}
      cloudify_password: {{ .Values.db.cloudify_password }}
      ssl_enabled: true
      ssl_client_verification: true
    postgresql_server:
      ca_path: '/etc/cloudify/ca.pem'
      cert_path: '/etc/cloudify/external-cert.pem'
      key_path: '/etc/cloudify/external-key.pem'

    prometheus:
      ca_path: '/etc/cloudify/ca.pem'
      cert_path: '/etc/cloudify/external-cert.pem'
      key_path: '/etc/cloudify/external-key.pem'
      scrape_interval: 5s

    ssl_inputs:
      postgresql_client_cert_path: /etc/cloudify/postgres-client-cert.pem
      postgresql_client_key_path: /etc/cloudify/postgres-client-key.pem
      postgresql_ca_cert_path: /etc/cloudify/postgresql-ca-cert.pem
      ca_cert_path: /etc/cloudify/ca.pem
      internal_cert_path: /etc/cloudify/cert.pem
      internal_key_path: /etc/cloudify/key.pem
      external_cert_path: /etc/cloudify/external-cert.pem
      external_key_path: /etc/cloudify/external-key.pem
      external_ca_cert_path: /etc/cloudify/ca.pem

    validations:
      skip_validations: true

    services_to_install:
    - manager_service
    - monitoring_service

    service_management: systemd