{{- if $.Values.nginx.fastly.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: sigsci.fusion
stringData:
  accesskeyid: {{ $.Values.nginx.fastly.accesskeyid }}
  secretaccesskey: {{ $.Values.nginx.fastly.secretaccesskey }}
{{- end }}