apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
{{ include "cloudify-manager-worker.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.port }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.https.port }}
      targetPort: {{ .Values.service.https.port }}
      protocol: TCP
      name: https
    - port: {{ .Values.service.internalRest.port }}
      targetPort: {{ .Values.service.internalRest.port }}
      protocol: TCP
      name: internal-rest
    {{- if .Values.service.extraPort }}
    {{- range .Values.service.extraPorts }}
    - {{ . }}
    {{- end}}
    {{- end}}
    
  selector:
    app: {{ template "cloudify-manager-worker.name" . }}
