apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "cloudify-manager-worker.name" . }}
  labels:
    name: {{ template "cloudify-manager-worker.name" . }}
{{ include "cloudify-manager-worker.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "cloudify-manager-worker.name" . }}
  serviceName: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ template "cloudify-manager-worker.name" . }}
    spec:
      initContainers:
      - name: init-data
        image: busybox
        command:
          - /bin/sh
          - -cx
          - |
            mkdir -p /mnt/cloudify-data/ssl
            cp /tmp/ssl/* /mnt/cloudify-data/ssl
        volumeMounts:
        - name: cfy-worker-certs
          mountPath: /tmp/ssl
        - name: cloudify-data
          mountPath: /mnt/cloudify-data
      containers:
      - name: {{ template "cloudify-manager-worker.name" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /run
          name: run
        - mountPath: /run/lock
          name: runlock
        - name: cloudify-cfg-volume
          mountPath: /tmp/cloudify/config.yaml
          subPath: config.yaml
        - name: supervisord-volume
          mountPath: /etc/supervisord.conf
          subPath: supervisord.conf
        - name: cfy-starter-volume
          mountPath: /tmp/cloudify/cfy_starter.sh
          subPath: cfy_starter.sh
        - name: before-hook-volume
          mountPath: /tmp/cloudify/before_hook.sh
          subPath: before_hook.sh
        - name: after-hook-volume
          mountPath: /tmp/cloudify/after_hook.sh
          subPath: after_hook.sh
        - name: cloudify-data
          mountPath: /mnt/cloudify-data
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]
      volumes:
      - name: run
        emptyDir:
          medium: Memory
          sizeLimit: "2Gi"
      - name: runlock
        emptyDir:
          medium: Memory
          sizeLimit: "2Gi"
      - name: cloudify-cfg-volume
        configMap:
          name: cloudify-config
      - name: supervisord-volume
        configMap:
          name: supervisord-config
      - name: cfy-starter-volume
        projected:
          defaultMode: 0754
          sources:
          - configMap:
              name: cfy-starter
      - name: before-hook-volume
        projected:
          defaultMode: 0754
          sources:
          - configMap:
              name: before-hook
      - name: after-hook-volume
        projected:
          defaultMode: 0754
          sources:
          - configMap:
              name: after-hook
      - name: cfy-worker-certs
        secret:
          secretName: cfy-worker-certs
    {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
    {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: cloudify-data
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: {{ .Values.volume.size }}