apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "cloudify-manager-worker.name" . }}
  labels:
    name: {{ template "cloudify-manager-worker.name" . }}
{{ include "cloudify-manager-worker.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.config.replicas }}
  selector:
    matchLabels:
      app: {{ template "cloudify-manager-worker.name" . }}
  serviceName: {{ .Values.service.name }}
  template:
    metadata:
      annotations:
        ad.datadoghq.com/{{ template "cloudify-manager-worker.name" . }}.logs: |
          [{
              "type": "file",
              "path": "/var/log/cloudify/manager/cfy_manager.log",
              "source": "file",
              "service": "cfy-manager"
          },
          {
              "type": "file",
              "path": "/var/log/cloudify/ampq-postgres/ampg_postgres.log",
              "source": "file",
              "service": "ampq-postgres"
          },
          {
              "type": "file",
              "path": "/var/log/cloudify/composer/app.log",
              "source": "file",
              "service": "composer-app"
          },
          {
              "type": "file",
              "path": "/var/log/cloudify/composer/errors.log",
              "source": "file",
              "service": "composer-errors"
          },
          {
              "type": "file",
              "path": "/var/log/cloudify/execution-scheduler/scheduler.log",
              "source": "file",
              "service": "execution-scheduler"
          },
          {
              "type": "file",
              "path": "/var/log/cloudify/nginx/cloudify.access.log",
              "source": "file",
              "service": "nginx-cloudify-access"
          },
          {
              "type": "file",
              "path": "/var/log/cloudify/nginx/access.log",
              "source": "file",
              "service": "nginx-access"
          },
          {
              "type": "file",
              "path": "/var/log/cloudify/nginx/cloudify.error.log",
              "source": "file",
              "service": "nginx-cloudify-error"
          },
          {
              "type": "file",
              "path": "/var/log/cloudify/nginx/error.log",
              "source": "{{ template "cloudify-manager-worker.name" . }}",
              "service": "nginx-error"
          },
          {
              "type": "file",
              "path": "/var/log/cloudify/nginx/monitoring.access.log",
              "source": "{{ template "cloudify-manager-worker.name" . }}",
              "service": "nginx-monitoring-access"
          },
          {
              "type": "file",
              "path": "/var/log/cloudify/nginx/monitoring.error.log",
              "source": "{{ template "cloudify-manager-worker.name" . }}",
              "service": "nginx-monitoring-error"
          },
          {
              "type": "file",
              "path": "/var/log/cloudify/rest/api-audit.log",
              "source": "{{ template "cloudify-manager-worker.name" . }}",
              "service": "rest-api-audit"
          },
          {
              "type": "file",
              "path": "/var/log/cloudify/rest/api-gunicorn.log",
              "source": "{{ template "cloudify-manager-worker.name" . }}",
              "service": "rest-api-gunicorn"
          },
          {
              "type": "file",
              "path": "/var/log/cloudify/rest/audit.log",
              "source": "{{ template "cloudify-manager-worker.name" . }}",
              "service": "rest-audit"
          },
          {
            "type": "file",
            "path": "/var/log/cloudify/rest/cloudify-api-service.log",
            "source": "{{ template "cloudify-manager-worker.name" . }}",
            "service": "rest-cloudify-api-service"
          },
          {
            "type": "file",
            "path": "/var/log/cloudify/rest/cloudify-rest-service.log",
            "source": "{{ template "cloudify-manager-worker.name" . }}",
            "service": "rest-cloudify-rest-service"
          },
          {
            "type": "file",
            "path": "/var/log/cloudify/rest/gunicorn.log",
            "source": "{{ template "cloudify-manager-worker.name" . }}",
            "service": "rest-gunicorn"
          },
          {
            "type": "file",
            "path": "/var/log/cloudify/stage/server-error.log",
            "source": "{{ template "cloudify-manager-worker.name" . }}",
            "service": "stage-server-error"
          },
          {
            "type": "file",
            "path": "/var/log/cloudify/stage/server-output.log",
            "source": "{{ template "cloudify-manager-worker.name" . }}",
            "service": "stage-server-output"
          },
          {
            "source":"{{ template "cloudify-manager-worker.name" . }}",
            "service":"cfy-manager"
          }] 
      labels:
        app: {{ template "cloudify-manager-worker.name" . }}
        {{- if .Values.config.labels }}
        {{- toYaml .Values.config.labels | nindent 8 }}
        {{- end }}
    spec:
      automountServiceAccountToken: false
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      {{- if .Values.initContainers.waitDependencies.enabled }}
      - name: wait-for-dependencies
        image: {{ .Values.initContainers.waitDependencies.repository }}:{{ .Values.initContainers.waitDependencies.tag }}
        imagePullPolicy: {{ .Values.initContainers.waitDependencies.pullPolicy }}
        {{- if .Values.initContainers.waitDependencies.resources }}
        resources: {{- toYaml .Values.initContainers.waitDependencies.resources | nindent 10 }}
        {{- end }}
        securityContext: {{- toYaml .Values.containerSecurityContext | nindent 10 }}
        env:
        - name: POSTGRES_HOST
          value: {{ .Values.db.host }}
        - name: RABBIT_HOST
          value: {{ .Values.queue.host }}
        command:
          - /bin/sh
          - -c
          - |
            timeout {{ .Values.initContainers.waitDependencies.timeout }} /bin/sh -c '
              wait_for_service(){
                SERVICE="$1:$2"
                until nc -vz $SERVICE > /dev/null; do
                  >&2 echo "$SERVICE is unavailable - sleeping"
                  sleep 2
                done
                >&2 echo "$SERVICE is up"
              }
              wait_for_service ${POSTGRES_HOST} "5432"
              wait_for_service ${RABBIT_HOST} "15671"
            '
        {{- end }}
      containers:
      - name: {{ template "cloudify-manager-worker.name" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.httpGet.path }}
            port: {{ .Values.livenessProbe.httpGet.port }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.httpGet.path }}
            port: {{ .Values.readinessProbe.httpGet.port }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
        {{- end }}
        {{- if .Values.startupProbe.enabled }}
        startupProbe:
          httpGet:
            path: {{ .Values.startupProbe.httpGet.path }}
            port: {{ .Values.startupProbe.httpGet.port }}
          timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
          successThreshold: {{ .Values.startupProbe.successThreshold }}
          periodSeconds: {{ .Values.startupProbe.periodSeconds }}
          failureThreshold: {{ .Values.startupProbe.failureThreshold }}
          initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
        {{- end }}
        {{- if .Values.resources }}
        resources: {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
        securityContext: {{- toYaml .Values.containerSecurityContext | nindent 10 }}
        volumeMounts:
        - mountPath: /tmp/log
          name: applogs
        - mountPath: /run
          name: run
        - mountPath: /run/lock
          name: runlock
        - name: cloudify-cfg-volume
          mountPath: /tmp/cloudify/config.yaml
          subPath: config.yaml
        {{- if .Values.license }}
        - name: cloudify-license-volume
          mountPath: /tmp/cloudify/cfy_license.yaml
          subPath: cfy_license.yaml
        {{- else if .Values.licence }}
        - name: cloudify-licence-volume
          mountPath: /tmp/cloudify/cfy_licence.yaml
          subPath: cfy_licence.yaml
        {{- end }}
        - name: supervisord-volume
          mountPath: /etc/supervisord.d/starter.conf
          subPath: starter.conf
        - name: cfy-starter-volume
          mountPath: /tmp/cloudify/cfy_starter.sh
          subPath: cfy_starter.sh
        - name: before-hook-volume
          mountPath: /tmp/cloudify/before_hook.sh
          subPath: before_hook.sh
        - name: after-hook-volume
          mountPath: /tmp/cloudify/after_hook.sh
          subPath: after_hook.sh
        - name: cloudify-data
          mountPath: /mnt/cloudify-data
        - name: cfy-worker-certs
          mountPath: {{ .Values.config.tlsCertPath }}
          subPath: tls.crt
        - name: cfy-worker-certs
          mountPath: {{ .Values.config.tlsKeyPath }}
          subPath: tls.key
        - name: cfy-worker-certs
          mountPath: {{ .Values.config.caCertPath }}
          subPath: ca.crt
        {{- if .Values.okta.enabled }}
        - name: okta-license-volume
          mountPath: /mnt/cloudify-data/ssl/okta_certificate.pem
          subPath: okta_certificate.pem
        {{- end }}
        - name: stage-user-config-volume
          mountPath: /tmp/cloudify/userConfig.json
          subPath: userConfig.json
        {{- if .Values.db.useExternalDB }}
        - name: cfy-pgsql-cert
          mountPath: /mnt/cloudify-data/ssl/postgres_ca.crt
          subPath: {{ .Values.tls.pgsqlSslCaName }}
        {{- if ne .Values.tls.pgsqlSslCertName "" }}
        - name: cfy-pgsql-cert
          mountPath: /mnt/cloudify-data/ssl/postgres.crt
          subPath: {{ .Values.tls.pgsqlSslCertName }}
        {{- end }}
        {{- if ne .Values.tls.pgsqlSslKeyName "" }}
        - name: cfy-pgsql-cert
          mountPath: /mnt/cloudify-data/ssl/postgres.key
          subPath: {{ .Values.tls.pgsqlSslKeyName }}
        {{- end }}
        {{- end }}
        {{- if .Values.additionalSecrets }}
        {{- range $index, $secret := .Values.additionalSecrets }}
        {{- range $key, $mount := $secret.mounts }}
        - name: {{ $secret.name }}
          mountPath: {{ $mount.mountPath }}
          subPath: {{ $mount.subPath }}
        {{- end }}
        {{- end }}
        {{- end }}
      volumes:
      - name: applogs
        hostPath:
          path: /tmp/log      
      - name: run
        emptyDir:
          medium: Memory
          sizeLimit: "2Gi"
      - name: runlock
        emptyDir:
          medium: Memory
          sizeLimit: "2Gi"
      - name: cloudify-cfg-volume
        configMap:
          name: cloudify-config
      {{- if .Values.license.useSecret }}
      - name: cloudify-license-volume
        secret:
          secretName: {{ .Values.license.secretName }}
      {{- else if .Values.license }}
      - name: cloudify-license-volume
        configMap:
          name: {{ .Values.license.secretName }}
      {{- end }}
      {{- if .Values.okta.enabled }}
      - name: okta-license-volume
        secret:
          secretName: {{ .Values.okta.secretName }}
      {{- end }}
      - name: stage-user-config-volume
        configMap:
          name: user-config
      - name: supervisord-volume
        configMap:
          name: supervisord-config
      - name: cfy-starter-volume
        projected:
          defaultMode: 0754
          sources:
          - configMap:
              name: cfy-starter
      - name: before-hook-volume
        projected:
          defaultMode: 0754
          sources:
          - configMap:
              name: before-hook
      - name: after-hook-volume
        projected:
          defaultMode: 0754
          sources:
          - configMap:
              name: after-hook
      - name: cfy-worker-certs
        secret:
          secretName: {{ .Values.tls.secretName }}
      - name: cloudify-data
        persistentVolumeClaim:
          claimName: cfy-worker-pvc
      {{- if .Values.db.useExternalDB }}
      - name: cfy-pgsql-cert
        secret:
          secretName: {{ .Values.tls.pgsqlSslSecretName }}
      {{- end }}
      {{- if .Values.additionalSecrets }}
      {{- range $index, $secret := .Values.additionalSecrets }}
      - name: {{ $secret.name }}
        secret: 
          secretName: {{ $secret.name }}
      {{- end }}
      {{- end }}

    {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
    {{- end }}
    {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.pullSecrets | indent 8 }}
      {{- end }}