apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "cloudify-manager-worker.name" . }}
  labels:
    name: {{ template "cloudify-manager-worker.name" . }}
{{ include "cloudify-manager-worker.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "cloudify-manager-worker.name" . }}
  serviceName: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ template "cloudify-manager-worker.name" . }}
    spec:
      containers:
      - name: {{ template "cloudify-manager-worker.name" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pull_policy }}
        volumeMounts:
        - mountPath: /run
          name: run
        - mountPath: /run/lock
          name: runlock
        - name: cloudify-config
          mountPath: /tmp/cloudify/config.yaml
          subPath: config.yaml
        - name: supervisord-config
          mountPath: /etc/supervisord.conf
          subPath: supervisord.conf
        - name: cfy-starter
          mountPath: /tmp/cloudify/cfy_starter.sh
          subPath: cfy_starter.sh
        - name: before-hook
          mountPath: /tmp/cloudify/before_hook.sh
          subPath: before_hook.sh
        - name: after-hook
          mountPath: /tmp/cloudify/after_hook.sh
          subPath: after_hook.sh
        - name: one-key
          mountPath: /tmp/cloudify/one-key.pem
          subPath: one-key.pem
        - name: one-cert
          mountPath: /tmp/cloudify/one-cert.pem
          subPath: one-cert.pem
        - name: ca-cert
          mountPath: /tmp/cloudify/ca-cert.pem
          subPath: ca-cert.pem
        - mountPath: /mnt/cloudify-data
          name: cloudify-data
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]
      volumes:
      - name: run
        emptyDir:
          medium: Memory
          sizeLimit: "2Gi"
      - name: runlock
        emptyDir:
          medium: Memory
          sizeLimit: "2Gi"
      - name: cloudify-config
        configMap:
          name: cloudify-config
      - name: supervisord-config
        configMap:
          name: supervisord-config
      - name: cfy-starter
        projected:
          defaultMode: 0754
          sources:
          - configMap:
              name: cfy-starter
      - name: before-hook
        projected:
          defaultMode: 0754
          sources:
          - configMap:
              name: before-hook
      - name: after-hook
        projected:
          defaultMode: 0754
          sources:
          - configMap:
              name: after-hook
      - name: one-key
        projected:
          defaultMode: 0754
          sources:
          - configMap:
              name: one-key
      - name: one-cert
        projected:
          defaultMode: 0754
          sources:
          - configMap:
              name: one-cert
      - name: ca-cert
        projected:
          defaultMode: 0754
          sources:
          - configMap:
              name: ca-cert
      nodeSelector:
        instance-type: spot
  volumeClaimTemplates:
  - metadata:
      name: cloudify-data
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: "8Gi"