apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: supervisord-config
data:
  starter.conf: |
    [program:cloudify-starter]
    command=/tmp/cloudify/cfy_starter.sh
    stdout_logfile=/dev/fd/1
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/fd/2
    stderr_logfile_maxbytes=0
    startsecs=0
    autorestart=false

    [program:cron]
    command=/usr/sbin/crond -n
    autostart=true
    autorestart=true
    startsecs=30
    stderr_logfile=/var/log/cron.err.log
    stdout_logfile=/var/log/cron.out.log

    [program:log-monitor]
    command=/tmp/cloudify/cfy_log_monitoring.sh
    autostart=true
    autorestart=true
    startsecs=30
    stderr_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stdout_logfile=/dev/stderr
    stderr_logfile_maxbytes=0