apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: systemd-script
data:
  script.sh: |
    #!/usr/bin/env bash
    echo "Copy config and certs!"
    
    rm -f /etc/cloudify/config.yaml
    cp  /tmp/cloudify/config.yaml /etc/cloudify/config.yaml
    sudo chown cfyuser /etc/cloudify/config.yaml
    
    cp /tmp/cloudify/one-key.pem /etc/cloudify/postgres-client-key.pem
    cp /tmp/cloudify/one-key.pem /etc/cloudify/key.pem
    cp /tmp/cloudify/one-key.pem /etc/cloudify/external-key.pem

    cp /tmp/cloudify/one-cert.pem /etc/cloudify/postgres-client-cert.pem
    cp /tmp/cloudify/ca-cert.pem /etc/cloudify/postgresql-ca-cert.pem
    cp /tmp/cloudify/ca-cert.pem /etc/cloudify/ca.pem
    cp /tmp/cloudify/one-cert.pem /etc/cloudify/cert.pem
    cp /tmp/cloudify/one-cert.pem /etc/cloudify/external-cert.pem

    mkdir -p /etc/cloudify/ssl
    cp /tmp/cloudify/ca-cert.pem /etc/cloudify/ssl/postgresql_ca.crt
    sudo chown cfyuser /etc/cloudify/ssl/postgresql_ca.crt
