apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: cfy-before-script
data:
  before_script.sh: |
    #!/usr/bin/env bash

    FILE=/mnt/cloudify-data/init-completed
    CLOUDIFY_DATA_DIR="/mnt/cloudify-data"
    mkdir -p /etc/cloudify/ssl

    if [ -f "$FILE" ]; then
      cp -a --verbose "$CLOUDIFY_DATA_DIR/config.yaml" /etc/cloudify/config.yaml
      cp -a --verbose "$CLOUDIFY_DATA_DIR/ssl" /etc/cloudify/ssl
    else 
        echo "Copy config"
        rm -f /etc/cloudify/config.yaml
        cp /tmp/cloudify/config.yaml /etc/cloudify/config.yaml
        sudo chown cfyuser /etc/cloudify/config.yaml
        
        echo "Copy certificates"
        cp /tmp/cloudify/one-key.pem /etc/cloudify/ssl/postgres-client-key.pem
        cp /tmp/cloudify/one-key.pem /etc/cloudify/ssl/key.pem
        cp /tmp/cloudify/one-key.pem /etc/cloudify/ssl/external-key.pem

        cp /tmp/cloudify/one-cert.pem /etc/cloudify/ssl/postgres-client-cert.pem
        cp /tmp/cloudify/ca-cert.pem /etc/cloudify/ssl/postgresql-ca-cert.pem
        cp /tmp/cloudify/ca-cert.pem /etc/cloudify/ssl/ca.pem
        cp /tmp/cloudify/one-cert.pem /etc/cloudify/ssl/cert.pem
        cp /tmp/cloudify/one-cert.pem /etc/cloudify/ssl/external-cert.pem

        cp /tmp/cloudify/ca-cert.pem /etc/cloudify/ssl/postgresql_ca.crt
        sudo chown cfyuser /etc/cloudify/ssl/postgresql_ca.crt

        cp /tmp/cloudify/ca-cert.pem /opt/cloudify-stage/conf/db_ca.crt
        sudo chown cfyuser /opt/cloudify-stage/conf/db_ca.crt

        cp /tmp/cloudify/ca-cert.pem /opt/cloudify-composer/backend/conf/db_ca.crt
        sudo chown cfyuser /opt/cloudify-composer/backend/conf/db_ca.crt
    fi
