nameOverride: ""
fullnameOverride: ""

image:
  repository: "cloudifyplatform/community-cloudify-manager-aio"
  tag: "6.4.2"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  name: cloudify-manager-aio
  rabbitmq:
    port: 5671
  http:
    port: 80
  https:
    port: 443
  internalRest:
    port: 53333

nodeSelector: {}

resources:
  requests:
    memory: 1Gi
    cpu: 0.5
  limits:
    memory: 6Gi
    cpu: 3

# -- Parameters group for pod startup probe
# @default -- object
startupProbe:
  # -- Enable startup probe
  enabled: true
  httpGet:
    # -- startup probe HTTP GET path
    path: /console
  # -- startup probe timeout in seconds
  timeoutSeconds: 5
  # -- startup probe success threshold
  successThreshold: 1
  # -- startup probe period in seconds
  periodSeconds: 10
  # -- startup probe failure threshold
  failureThreshold: 30
  # -- startup probe initial delay in seconds
  initialDelaySeconds: 30

# -- Parameters group for pod readiness probe
# @default -- object
readinessProbe:
  # -- Enable readiness probe
  enabled: true
  httpGet:
    # -- readiness probe HTTP GET path
    path: /console
  # -- readiness probe timeout in seconds
  timeoutSeconds: 5
  # -- readiness probe success threshold
  successThreshold: 2
  # -- readiness probe period in seconds
  periodSeconds: 10
  # -- readiness probe failure threshold
  failureThreshold: 2
  # -- readiness probe initial delay in seconds
  initialDelaySeconds: 0

# -- Parameters group for pod liveness probe
# @default -- object
livenessProbe:
  # -- Enable liveness probe
  enabled: false
  httpGet:
    # -- liveness probe HTTP GET path
    path: /api/v3.1/ok
  # -- liveness probe timeout in seconds
  timeoutSeconds: 15
  # -- liveness probe success threshold
  successThreshold: 1
  # -- liveness probe period in seconds
  periodSeconds: 30
  # -- liveness probe failure threshold
  failureThreshold: 8
  # -- liveness probe initial delay in seconds
  initialDelaySeconds: 600

podSecurityContext:
  runAsNonRoot: false
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: false
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
      - ALL
    add:
      - CHOWN
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - DAC_OVERRIDE
      - DAC_READ_SEARCH
      - FOWNER
      - FSETID
      - SETUID
      - SETGID
      - SETFCAP
      - SETPCAP
      - AUDIT_WRITE
