nameOverride: ""
fullnameOverride: ""

namespace: ""

image:
  repository: "cloudifyplatform/community-cloudify-manager-aio"
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  name: cloudify-manager-aio
  rabbitmq:
    port: 5671
  http:
    port: 80
  https:
    port: 443
  internalRest:
    port: 53333

nodeSelector: {}

resources: {}
  # requests:
  #   memory: 0.5Gi
  #   cpu: 0.5
  # limits:
  #   memory: 0.5Gi
  #   cpu: 0.5

readinessProbe:
  enabled: true
  port: 80
  path: /console
  initialDelaySeconds: 10
