nameOverride: "cloudify-manager-worker"
fullnameOverride: "cloudify-manager-worker"

image:
  repository: cloudifyplatform/premium-cloudify-manager-worker
  tag: 5.3.0
  pullPolicy: Always

db:
  host: postgres-postgresql
  cloudifyDBName: 'cloudify_db'
  cloudifyUsername: 'cloudify'
  cloudifyPassword: 'cloudify'
  serverDBName: 'postgres'
  serverUsername: 'postgres'
  serverPassword: 'cfy_test_pass'

queue:
  host: rabbitmq
  username: 'cfy_user'
  password: 'cfy_test_pass'

service:
  host: cloudify-manager-worker
  type: LoadBalancer
  name: cloudify-manager-worker
  http:
    port: 80
  https:
    port: 443
  internalRest:
    port: 53333

nodeSelector: {}

secret:
  name: cfy-certs

# Multiple replicas - EFS only, storageClass: 'aws-efs', accessMode: 'ReadWriteMany'
# Single replica - EBS, storageClass: 'gp2', accessMode: 'ReadWriteOnce'
volume:
  storageClass: 'nfs-client'
  accessMode: 'ReadWriteMany'
  size: "15Gi"

resources:
  requests:
    memory: 0.1Gi
    cpu: 0.1

config:
  # Multiple replicas works only with NFS storage
  replicas: 2
  startDelay: 0
  installPlugins: false
  cliLocalProfileHostName: localhost
  security:
    sslEnabled: false
    adminPassword: admin
  tlsCertPath: /mnt/cloudify-data/ssl/tls.crt
  tlsKeyPath: /mnt/cloudify-data/ssl/tls.key
  caCertPath: /mnt/cloudify-data/ssl/ca.crt

readinessProbe:
  enabled: true
  port: 80
  path: /console
  successThreshold: 3
  initialDelaySeconds: 10

ingress:
  enabled: false
  host: cfy-efs-app.eks.cloudify.co
  annotations:
    kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    enabled: false
    secretName: cfy-secret-name
