kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cm-efs
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: EFS_ID
  directoryPerms: "700"
  gid: "0"
  uid: "0"
  basePath: "/dynamic_provisioning"
