apiVersion: v2
name: cloudify-services
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "7.0.3"

dependencies:
  - condition: seaweedfs.enabled
    name: seaweedfs
    version: 3.55
    repository: https://seaweedfs.github.io/seaweedfs/helm

  - condition: postgresql.enabled
    name: postgresql
    version: 12.6.5
    repository: https://charts.bitnami.com/bitnami

  - condition: rabbitmq.enabled
    name: rabbitmq
    version: 12.0.9
    repository: https://charts.bitnami.com/bitnami

  - condition: prometheus.enabled
    name: prometheus
    version: 0.1.6
    repository: https://charts.bitnami.com/bitnami
