apiVersion: v2
name: cloudify-services
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "7.0.3"

dependencies:
  - condition: seaweedfs.enabled
    name: seaweedfs
    version: 3.55
    repository: https://seaweedfs.github.io/seaweedfs/helm
