rabbitmq:
  replicaCount: 1
  initContainers:
    - name: ipv6-init
      image: "docker.io/busybox:1.33.1"
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - name: ipv6-cfg
        mountPath: /ipv6
      command: ['sh', '-c', 'echo "{inet6, true}." > /ipv6/erl_inetrc']
  extraVolumes:
    - name: ipv6-cfg
      emptyDir: {}
  extraVolumeMounts:
    - name: ipv6-cfg
      mountPath: /ipv6
  extraEnvVars:
    - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
      value: "-kernel inetrc '/ipv6/erl_inetrc' -proto_dist inet6_tcp"
    - name: RABBITMQ_CTL_ERL_ARGS
      value: "-proto_dist inet6_tcp"
  extraConfiguration: |-
    management.ssl.ip         = ::
    management.ssl.port       = 15671
    management.ssl.cacertfile = /opt/bitnami/rabbitmq/certs/ca_certificate.pem
    management.ssl.certfile   = /opt/bitnami/rabbitmq/certs/server_certificate.pem
    management.ssl.keyfile    = /opt/bitnami/rabbitmq/certs/server_key.pem
