imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: { }
  name: ""

service:
  type: ClusterIP
  port: 80
  http:
    port: 80

ingress:
  enabled: true
  host:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
  tls:
    enabled: false
    secretName: cfy-secret-name

certs:
  ca_cert: ""
  ca_key: ""
  external_cert: ""
  external_key: ""
  internal_cert: ""
  internal_key: ""
  rabbitmq_cert: ""
  rabbitmq_key: ""

resources:
  packages:
    agents:
      manylinux-x86_64-agent.tar.gz: https://cloudify-release-eu.s3.amazonaws.com/cloudify/7.0.0/ga-release/manylinux-x86_64-agent_7.0.0-ga.tar.gz
      manylinux-aarch64-agent.tar.gz: https://cloudify-release-eu.s3.amazonaws.com/cloudify/7.0.0/ga-release/manylinux-aarch64-agent_7.0.0-ga.tar.gz
      cloudify-windows-agent.exe: https://cloudify-release-eu.s3.amazonaws.com/cloudify/7.0.0/ga-release/cloudify-windows-agent_7.0.0-ga.exe

composer_backend:
  replicas: 1
  image: 263721492972.dkr.ecr.eu-west-1.amazonaws.com/cloudify-manager-composer-backend:7.0.3-dev1
  imagePullPolicy: IfNotPresent
  port: 3000
  probes:
    liveness:
      enabled: false
      initialDelaySeconds: 20
      periodSeconds: 20
      timeoutSeconds: 10
      successThreshold: 1
      failureThreshold: 3
  securityContext:
    runAsNonRoot: true

composer_frontend:
  replicas: 1
  image: 263721492972.dkr.ecr.eu-west-1.amazonaws.com/cloudify-manager-composer-frontend:7.0.3-dev1
  imagePullPolicy: IfNotPresent
  port: 8188
  probes:
    liveness:
      enabled: true
      initialDelaySeconds: 20
      periodSeconds: 20
      timeoutSeconds: 10
      successThreshold: 1
      failureThreshold: 3
  securityContext:
    runAsNonRoot: true

execution_scheduler:
  replicas: 1
  image: 263721492972.dkr.ecr.eu-west-1.amazonaws.com/cloudify-manager-execution-scheduler:7.0.3-dev1
  imagePullPolicy: IfNotPresent

mgmtworker:
  replicas: 1
  image: 263721492972.dkr.ecr.eu-west-1.amazonaws.com/cloudify-manager-mgmtworker:7.0.3-dev1
  imagePullPolicy: IfNotPresent
  access:
    local_cluster: true

nginx:
  replicas: 1
  image: docker.io/library/nginx
  imagePullPolicy: IfNotPresent
  http_port: 80
  https_port: 443
  internal_port: 53333
  probes:
    liveness:
      enabled: true
      initialDelaySeconds: 20
      periodSeconds: 20
      timeoutSeconds: 10
      successThreshold: 1
      failureThreshold: 3
  # configure request rate-limits. If enabled, requests are rate-limited based
  # on the remote IP address.
  # Requests that authenticate with a valid execution-token, are never
  # rate-limited
  rate_limit:
    enabled: true
    # rate is a string in the form of "10r/s" (10 requests per second)
    # or "600r/m" (600 requests per minute)
    rate: "10r/s"
    # burst and delay manage the request queueing mechanism. With the
    # default settings of burst=30 and delay=20, up to 30 requests
    # can be queued per IP (i.e. before nginx starts responding with 503),
    # and the first 20 requests will be served without any delay. Then, requests
    # will be delayed according to the rate, and if there's more than 30 queued
    # total, will receive 503.
    burst: 30

    delay: 20
db:
  host: "postgresql"
  dbName: &postgresqlDB "cloudify_db"
  user: &postgresqlUser "cloudify"
  password: &postgresqlPassword "cloudify"
  k8sSecret:
    name: "cloudify-db-creds"
    key: "password"


postgresql:
  enabled: true
  fullnameOverride: postgresql
  auth:
    username: *postgresqlUser
    database: *postgresqlDB
    password: *postgresqlPassword
  image:
    tag: 15.3.0-debian-11-r17
    pullPolicy: IfNotPresent
  containerPorts:
    postgresql: 5432
  primary:
    resources:
      limits:
        memory: 2Gi
        cpu: 2
      requests:
        memory: 256Mi
        cpu: 0.5
  podLabels: {}
  enableNetworkPolicy: true
  metrics:
    enabled: true

rabbitmq:
  enabled: true
  image:
    tag: 3.12.2-debian-11-r8
    pullPolicy: IfNotPresent
  fullnameOverride: rabbitmq
  plugins: "rabbitmq_management rabbitmq_prometheus rabbitmq_tracing rabbitmq_peer_discovery_k8s"
  auth:
    username: cloudify
    password: c10udify
    erlangCookie: "cloudify-erlang-cookie"
    tls:
      enabled: true
      failIfNoPeerCert: false
      existingSecret: rabbitmq-ssl-certs
  advancedConfiguration: |-
    [
      {rabbit, [
        {consumer_timeout, undefined}
      ]}
    ].
  extraConfiguration: |-
    management.ssl.port       = 15671
    management.ssl.cacertfile = /opt/bitnami/rabbitmq/certs/ca_certificate.pem
    management.ssl.certfile   = /opt/bitnami/rabbitmq/certs/server_certificate.pem
    management.ssl.keyfile    = /opt/bitnami/rabbitmq/certs/server_key.pem
  loadDefinition:
    enabled: true
    existingSecret: rabbitmq-load-definition
  extraSecrets:
    rabbitmq-load-definition:
      load_definition.json: |
        {
            "vhosts": [
                {
                    "name": "/"
                }
            ],
            "users": [
                {
                    "hashing_algorithm": "rabbit_password_hashing_sha256",
                    "name": "{{ .Values.auth.username }}",
                    "password": "{{ .Values.auth.password }}",
                    "tags": "administrator"
                }
            ],
            "permissions": [
                {
                    "user": "{{ .Values.auth.username }}",
                    "vhost": "/",
                    "configure": ".*",
                    "write": ".*",
                    "read": ".*"
                }
            ],
            "policies": [
                {
                    "name": "logs_queue_message_policy",
                    "vhost": "/",
                    "pattern": "^cloudify-log$",
                    "priority": 100,
                    "apply-to": "queues",
                    "definition": {
                        "message-ttl": 1200000,
                        "max-length": 1000000,
                        "ha-mode": "all",
                        "ha-sync-mode": "automatic",
                        "ha-sync-batch-size": 50
                    }
                },
                {
                    "name": "events_queue_message_policy",
                    "vhost": "/",
                    "pattern": "^cloudify-events$",
                    "priority": 100,
                    "apply-to": "queues",
                    "definition": {
                        "message-ttl": 1200000,
                        "max-length": 1000000,
                        "ha-mode": "all",
                        "ha-sync-mode": "automatic",
                        "ha-sync-batch-size": 50
                    }
                },
                {
                    "name": "default_policy",
                    "vhost": "/",
                    "pattern": "^",
                    "priority": 1,
                    "apply-to": "queues",
                    "definition": {
                        "ha-mode": "all",
                        "ha-sync-mode": "automatic",
                        "ha-sync-batch-size": 50
                    }
                }
            ],
            "queues": [
                {
                    "arguments": {},
                    "auto_delete": false,
                    "durable": true,
                    "name": "cloudify.management_operation",
                    "type": "classic",
                    "vhost": "/"
                },
                {
                    "arguments": {},
                    "auto_delete": false,
                    "durable": true,
                    "name": "cloudify.management_workflow",
                    "type": "classic",
                    "vhost": "/"
                }
            ],
            "bindings": [
                {
                    "arguments": {},
                    "destination": "cloudify.management_operation",
                    "destination_type": "queue",
                    "routing_key": "operation",
                    "source": "cloudify.management",
                    "vhost": "/"
                },
                {
                    "arguments": {},
                    "destination": "cloudify.management_workflow",
                    "destination_type": "queue",
                    "routing_key": "workflow",
                    "source": "cloudify.management",
                    "vhost": "/"
                }
            ],
            "exchanges": [
                {
                    "arguments": {},
                    "auto_delete": false,
                    "durable": true,
                    "name": "cloudify.management",
                    "type": "direct",
                    "vhost": "/"
                }
            ]
        }
  service:
    ports:
      metrics: 15692
    extraPorts:
      - name: manager-ssl
        port: 15671
        targetPort: 15671
  resources:
    requests:
      memory: 512Mi
      cpu: 0.5
    limits:
      memory: 1Gi
      cpu: 4
  podLabels: {}
  enableNetworkPolicy: true
  metrics:
    enabled: true

rest_service:
  replicas: 1
  image: 263721492972.dkr.ecr.eu-west-1.amazonaws.com/cloudify-manager-restservice:7.0.3-dev1
  imagePullPolicy: IfNotPresent
  port: 8100
  probes:
    liveness:
      enabled: false
      initialDelaySeconds: 20
      periodSeconds: 20
      timeoutSeconds: 10
      successThreshold: 1
      failureThreshold: 3
  configPath: /tmp/config.yaml
  s3:
    credentials_secret_name: seaweedfs-s3-secret
    session_token_secret_name: ""
  config:
    manager:
      hostname: cloudify-manager
      private_ip: localhost
      public_ip: localhost
      file_server_type: s3
      s3_resources_bucket: resources
      s3_server_url: http://seaweedfs-s3.default.svc.cluster.local:8333
      prometheus_url: http://prometheus:9090

api_service:
  replicas: 1
  image: 263721492972.dkr.ecr.eu-west-1.amazonaws.com/cloudify-manager-apiservice:7.0.3-dev1
  imagePullPolicy: IfNotPresent
  port: 8101
  probes:
    liveness:
      enabled: true
      initialDelaySeconds: 20
      periodSeconds: 20
      timeoutSeconds: 10
      successThreshold: 1
      failureThreshold: 3

stage_backend:
  replicas: 1
  image: 263721492972.dkr.ecr.eu-west-1.amazonaws.com/cloudify-manager-stage-backend:7.0.3-dev1
  imagePullPolicy: IfNotPresent
  port: 8088
  probes:
    liveness:
      enabled: true
      initialDelaySeconds: 20
      periodSeconds: 20
      timeoutSeconds: 10
      successThreshold: 1
      failureThreshold: 3
  securityContext:
    runAsNonRoot: true

stage_frontend:
  replicas: 1
  image: 263721492972.dkr.ecr.eu-west-1.amazonaws.com/cloudify-manager-stage-frontend:7.0.3-dev1
  imagePullPolicy: IfNotPresent
  port: 8188
  probes:
    liveness:
      enabled: true
      initialDelaySeconds: 20
      periodSeconds: 20
      timeoutSeconds: 10
      successThreshold: 1
      failureThreshold: 3
  securityContext:
    runAsNonRoot: true

prometheus:
  replicas: 1
  image: prom/prometheus
  imagePullPolicy: IfNotPresent
  api_port: 9090

# -- Parameters group for seaweed helm chart.
# Details: https://github.com/seaweedfs/seaweedfs/tree/master/k8s/charts/seaweedfs
# @default -- object
seaweedfs:
  enabled: true
  master:
    resources: |
      requests:
        memory: 128Mi
        cpu: 0.1
      limits:
        memory: 512Mi
        cpu: 0.5
    data:
      type: "persistentVolumeClaim"
      size: "1Gi"
    affinity: ""
    nodeSelector: ""
  filer:
    resources: |
      requests:
        memory: 128Mi
        cpu: 0.1
      limits:
        memory: 512Mi
        cpu: 0.5
    data:
      type: "persistentVolumeClaim"
      size: "1Gi"
    affinity: ""
    nodeSelector: ""
  s3:
    skipAuthSecretCreation: false
    enabled: true
    enableAuth: false
    port: 8333
    resources: |
      requests:
        memory: 128Mi
        cpu: 0.1
      limits:
        memory: 512Mi
        cpu: 0.5
    affinity: ""
    nodeSelector: ""
  volume:
    maxVolumes: "50"
    resources: |
      requests:
        memory: 256Mi
        cpu: 0.1
      limits:
        memory: 512Mi
        cpu: 0.5
    data:
      type: "persistentVolumeClaim"
      size: "10Gi"
    affinity: ""
    nodeSelector: ""
  # -- Parameters group for awscli containers (using as init containers)
  # @default -- object
  clientImage: docker.io/amazon/aws-cli:2.13.9
