replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  http:
    port: 80

ingress:
  enabled: true
  host:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
  tls:
    enabled: false
    secretName: cfy-secret-name

# These should be base64-encoded TLS certificates and keys
certs:
  ca_cert: ""
  ca_key: ""
  external_cert: ""
  external_key: ""
  internal_cert: ""
  internal_key: ""
  rabbitmq_cert: ""
  rabbitmq_key: ""

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

composer_backend:
  replicas: 1
  image: docker.io/library/composer_backend
  imagePullPolicy: IfNotPresent
  port: 3000
  restservice_address: nginx

composer_frontend:
  replicas: 1
  image: docker.io/library/composer_frontend
  imagePullPolicy: IfNotPresent
  port: 8188

execution_scheduler:
  replicas: 1
  image: docker.io/library/cloudify-manager-execution_scheduler
  imagePullPolicy: IfNotPresent

fileserver:
  replicas: 1
  image: docker.io/library/cloudify-manager-fileserver
  client_image: docker.io/bitnami/minio-client
  imagePullPolicy: IfNotPresent
  port:
    - 9000
    - 9090

mgmtworker:
  replicas: 1
  image: docker.io/library/cloudify-manager-mgmtworker
  imagePullPolicy: IfNotPresent

nginx:
  replicas: 1
  image: docker.io/library/cloudify-manager-nginx
  imagePullPolicy: IfNotPresent
  port:
    - 80
    - 443
    - 53333

postgresql:
  replicas: 1
  image: docker.io/library/postgres
  imagePullPolicy: IfNotPresent
  port: 5432
  postgres_db: cloudify_db
  postgres_password: cloudify
  postgres_user: cloudify

rabbitmq:
  replicas: 1
  image: docker.io/library/cloudify-manager-rabbitmq
  imagePullPolicy: IfNotPresent
  port:
    - 15671
    - 15692
    - 5671

rest_service:
  replicas: 1
  image: docker.io/library/cloudify-manager-rest_service
  imagePullPolicy: IfNotPresent
  port: 8100

stage_backend:
  replicas: 1
  image: docker.io/library/stage_backend
  imagePullPolicy: IfNotPresent
  port: 8088
  restservice_address: nginx

stage_frontend:
  replicas: 1
  image: docker.io/library/stage_frontend
  imagePullPolicy: IfNotPresent
  port: 8188
