replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  http:
    port: 80

ingress:
  enabled: true
  host:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
  tls:
    enabled: false
    secretName: cfy-secret-name

# These should be base64-encoded TLS certificates and keys
certs:
  ca_cert: ""
  ca_key: ""
  external_cert: ""
  external_key: ""
  internal_cert: ""
  internal_key: ""
  rabbitmq_cert: ""
  rabbitmq_key: ""

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

rabbitmq:
  replicas: 1

composer_backend:
  replicas: 1

composer_frontend:
  replicas: 1

fileserver:
  replicas: 1

nginx:
  replicas: 1

postgresql:
  replicas: 1

rest_service:
  replicas: 1

stage_backend:
  replicas: 1

stage_frontend:
  replicas: 1
