global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'cloudify'
    honor_labels: true
    static_configs:
      - targets: [ 'localhost:8000' ]

