apiVersion: v1
kind: Pod
metadata:
  labels:
    app: composer-backend
  name: composer-backend
spec:
  containers:
    - env:
        - name: RESTSERVICE_ADDRESS
          value: nginx
      image: docker.io/library/composer_backend
      imagePullPolicy: IfNotPresent
      name: composer-backend
      resources: {}
      ports:
        - containerPort: 3000
      volumeMounts:
        - mountPath: /etc/cloudify/ssl
          name: ssl
          readOnly: true
  restartPolicy: OnFailure
  volumes:
    - name: ssl
      secret:
        secretName: {{ template "cloudify-services.name" . }}-certs
        optional: false

---
apiVersion: v1
kind: Service
metadata:
  name: composer-backend
spec:
  ports:
    - port: 3000
  selector:
    app: composer-backend
  type: ClusterIP
