apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: composer-backend
  name: composer-backend
spec:
  replicas: {{ .Values.composer_backend.replicas }}
  selector:
    matchLabels:
      app: composer-backend
  template:
    metadata:
      labels:
        app: composer-backend
    spec:
      containers:
        - env:
            - name: RESTSERVICE_ADDRESS
              value: {{ .Values.composer_backend.restservice_address }}
          image: {{ .Values.composer_backend.image }}
          imagePullPolicy: {{ .Values.composer_backend.imagePullPolicy }}
          name: composer-backend
          ports:
            - containerPort: {{ .Values.composer_backend.port }}
          volumeMounts:
            - mountPath: /etc/cloudify/ssl
              name: ssl
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: ssl
          secret:
            secretName: {{ template "cloudify-services.name" . }}-certs
            optional: false

---
apiVersion: v1
kind: Service
metadata:
  name: composer-backend
spec:
  ports:
    - port: {{ .Values.composer_backend.port }}
  selector:
    app: composer-backend
  type: ClusterIP
