apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: composer-backend
  name: composer-backend
spec:
  replicas: {{ .Values.composer_backend.replicas }}
  selector:
    matchLabels:
      app: composer-backend
  template:
    metadata:
      labels:
        app: composer-backend
        cloudify-name: cloudify-composer
    spec:
      containers:
        - env:
            {{- include "cloudify-services.postgres_env_vars" . | nindent 12 }}
            - name: RESTSERVICE_ADDRESS
              value: cloudify-entrypoint
            - name: RESTSERVICE_PROTOCOL
              value: "http://"
            - name: RESTSERVICE_PORT
              value: "80"
          image: {{ .Values.composer_backend.image }}
          imagePullPolicy: {{ .Values.composer_backend.imagePullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          name: composer-backend
          ports:
            - containerPort: {{ .Values.composer_backend.port }}
          volumeMounts:
            - mountPath: /etc/cloudify/ssl
              name: ssl
              readOnly: true
          {{- if .Values.composer_backend.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              port: {{ .Values.composer_backend.port}}
              path: "/composer/backend/"
            initialDelaySeconds: {{ .Values.composer_backend.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.composer_backend.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.composer_backend.probes.liveness.timeoutSeconds }}
            successThreshold: {{ .Values.composer_backend.probes.liveness.successThreshold }}
            failureThreshold: {{ .Values.composer_backend.probes.liveness.failureThreshold }}
          {{- end }}
      restartPolicy: Always
      volumes:
        - name: ssl
          secret:
            secretName: {{ template "cloudify-services.name" . }}-certs
            optional: false
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: composer-backend
spec:
  ports:
    - port: {{ .Values.composer_backend.port }}
  selector:
    app: composer-backend
  type: ClusterIP
