apiVersion: v1
kind: Pod
metadata:
  labels:
    app: composer-frontend
  name: composer-frontend
spec:
  containers:
    - image: docker.io/library/composer_frontend
      imagePullPolicy: IfNotPresent
      name: composer-frontend
      resources: {}
      ports:
        - containerPort: 8188
  restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: composer-frontend
spec:
  ports:
    - port: 8188
  selector:
    app: composer-frontend
  type: ClusterIP
