apiVersion: v1
kind: Pod
metadata:
  labels:
    app: config
  name: config
spec:
  containers:
    - command:
        - /opt/rest-service/docker/entrypoint_config.sh
      env:
        - name: ENTRYPOINT
          value: localhost
      image: docker.io/library/cloudify-manager-config
      imagePullPolicy: IfNotPresent
      name: config
      resources: {}
      volumeMounts:
        - mountPath: /opt/manager
          name: manager-config
        - mountPath: /etc/cloudify/ssl
          name: ssl
          readOnly: true
        - mountPath: /mgmtworker
          name: mgmtworker-workdir
  restartPolicy: OnFailure
  volumes:
    - name: manager-config
      persistentVolumeClaim:
        claimName: manager-config
    - name: ssl
      persistentVolumeClaim:
        claimName: ssl
        readOnly: true
    - name: mgmtworker-workdir
      persistentVolumeClaim:
        claimName: mgmtworker-workdir

