{{- $db_creds_secret := (lookup "v1" "Secret" .Release.Namespace .Values.db.k8sSecret.name ) }}
{{- if not $db_creds_secret }}
apiVersion: v1
kind: Secret
type: opaque
metadata:
  name: {{ .Values.db.k8sSecret.name }}
  labels:
    app: {{ template "cloudify-services.name" . }}
    chart: {{ template "cloudify-services.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
stringData:
  {{ .Values.db.k8sSecret.key }}: {{ .Values.db.password }}
{{- end }}
