apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: execution-scheduler
  name: execution-scheduler
spec:
  replicas: {{ .Values.execution_scheduler.replicas }}
  selector:
    matchLabels:
      app: execution-scheduler
  template:
    metadata:
      labels:
        app: execution-scheduler
        cloudify-name: cloudify-execution-scheduler
    spec:
      containers:
        - image: {{ .Values.execution_scheduler.image }}
          imagePullPolicy: {{ .Values.execution_scheduler.imagePullPolicy }}
          name: execution-scheduler
      restartPolicy: Always
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}