apiVersion: v1
kind: Pod
metadata:
  labels:
    app: execution-scheduler
  name: execution-scheduler
spec:
  containers:
    - image: docker.io/library/cloudify-manager-execution_scheduler
      imagePullPolicy: IfNotPresent
      name: execution-scheduler
      resources: {}
  restartPolicy: Always
