apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileserver
  labels:
    app: fileserver
spec:
  replicas: {{ .Values.fileserver.replicas }}
  selector:
    matchLabels:
      app: fileserver
  template:
    metadata:
      labels:
        app: fileserver
    spec:
      containers:
        - image: {{ .Values.fileserver.image }}
          imagePullPolicy: {{ .Values.fileserver.imagePullPolicy }}
          name: fileserver
          ports:
            - containerPort: 9000
            - containerPort: 9090
          resources: {}
          volumeMounts:
            - mountPath: {{ .Values.fileserver.fileserverDataPath }}
              name: fileserver-data
      restartPolicy: Always
      volumes:
        - name: fileserver-data
          persistentVolumeClaim:
            claimName: fileserver-data

---
apiVersion: v1
kind: Service
metadata:
  name: fileserver
spec:
  ports:
    - name: "9000"
      port: 9000
    - name: "9090"
      port: 9090
  selector:
    app: fileserver
  type: ClusterIP
