apiVersion: v1
kind: Pod
metadata:
  name: fileserver
  labels:
    app: fileserver
spec:
  containers:
    - image: docker.io/library/cloudify-manager-fileserver
      imagePullPolicy: IfNotPresent
      name: fileserver
      ports:
        - containerPort: 9000
        - containerPort: 9090
      resources: {}
      volumeMounts:
        - mountPath: /data
          name: fileserver-data
  restartPolicy: Always
  volumes:
    - name: fileserver-data
      persistentVolumeClaim:
        claimName: fileserver-data

---
apiVersion: v1
kind: Service
metadata:
  name: fileserver
spec:
  ports:
    - name: "9000"
      port: 9000
    - name: "9090"
      port: 9090
  selector:
    app: fileserver
  type: NodePort
