apiVersion: v1
kind: Secret
type: opaque
metadata:
  name: clouodify-fileserver-credentials
  labels:
    app: {{ template "cloudify-services.name" . }}
    chart: {{ template "cloudify-services.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  AWS_ACCESS_KEY_ID: {{ (.Values.rest_service.s3.access_key_id | default (randAlphaNum 16 )) | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ (.Values.rest_service.s3.access_key_secret | default (randAlphaNum 32 )) | b64enc }}
  AWS_SESSION_TOKEN: {{ .Values.rest_service.s3.session_token | b64enc }}
