apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileserver
  labels:
    app: fileserver
spec:
  replicas: {{ .Values.fileserver.replicas }}
  selector:
    matchLabels:
      app: fileserver
  template:
    metadata:
      labels:
        app: fileserver
    spec:
      containers:
        - image: {{ .Values.fileserver.image }}
          imagePullPolicy: {{ .Values.fileserver.imagePullPolicy }}
          name: fileserver
          ports:
            {{- range .Values.fileserver.port }}
            - containerPort: {{ . }}
            {{- end }}
          volumeMounts:
            - mountPath: /data
              name: fileserver-data
      restartPolicy: Always
      volumes:
        - name: fileserver-data
          persistentVolumeClaim:
            claimName: fileserver-data

---
apiVersion: v1
kind: Service
metadata:
  name: fileserver
spec:
  ports:
    {{- range .Values.fileserver.port }}
    - name: {{ . | quote }}
      port: {{ . }}
    {{- end }}
  selector:
    app: fileserver
  type: ClusterIP
