# This is a secret used to populate ENCRYPTION_KEY environment variable in
# `rest-service` and `mgmtworker` deployments. It has to be double base64
# encoded: first b64enc is for Kubernetes, the second for Cloudify manager.
apiVersion: v1
kind: Secret
type: opaque
metadata:
  name: manager-security
  labels:
    app: {{ template "cloudify-services.name" . }}
    chart: {{ template "cloudify-services.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  encryptionKey: {{ ( randAlphaNum 64 ) | b64enc | b64enc }}
  secretKey: {{ ( randAlphaNum 64 ) | b64enc }}
  hashSalt: {{ ( randAlphaNum 64 ) | b64enc }}
