apiVersion: apps/v1
kind: Deployment
metadata:
  name: mgmtworker
spec:
  replicas: {{ .Values.mgmtworker.replicas }}
  selector:
    matchLabels:
      app: mgmtworker
  template:
    metadata:
      labels:
        app: mgmtworker
    spec:
      initContainers:
        - name: mgmtworker-init
          image: {{ .Values.rest_service.image }}
          imagePullPolicy: {{ .Values.rest_service.imagePullPolicy }}
          command:
            - /usr/bin/env
            - -S
            - bash
            - -exuc
            - |
              /opt/rest-service/docker/prepare_secrets.sh
              export "CONFIG_FILE=${CONFIG_FILE_PATH:-/tmp/config.yaml}"
              if [ ! -e "${CONFIG_FILE}" ] ; then
                echo "
                manager:
                  hostname: cloudify-manager
                  private_ip: ${ENTRYPOINT}
                  file_server_type: s3
                " > "${CONFIG_FILE}"
              fi
              python -m manager_rest.configure_manager --rabbitmq-wait rabbitmq
              python -m manager_rest.configure_manager -c /tmp/config.yaml --create-admin-token /opt/mgmtworker/work/admin_token
          env:
            - name: ENTRYPOINT
              value: nginx
          volumeMounts:
            - mountPath: /etc/cloudify/ssl
              name: ssl
              readOnly: true
            - mountPath: /opt/mgmtworker/work
              name: workdir-volume
      containers:
        - name: mgmtworker
          image: {{ .Values.mgmtworker.image }}
          imagePullPolicy: {{ .Values.mgmtworker.imagePullPolicy }}
          volumeMounts:
            - mountPath: /etc/cloudify/ssl
              name: ssl
              readOnly: true
            - mountPath: /opt/mgmtworker/work
              name: workdir-volume
      restartPolicy: Always
      volumes:
        - name: ssl
          secret:
            secretName: {{ template "cloudify-services.name" . }}-certs
            optional: false
        - name: workdir-volume
          emptyDir: {}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}