apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: {{ .Values.nginx.image }}
          imagePullPolicy: {{ .Values.nginx.imagePullPolicy }}
          name: nginx
          ports:
            {{- range .Values.nginx.port }}
            - containerPort: {{ . }}
            {{- end }}
          volumeMounts:
            - mountPath: /etc/cloudify/ssl
              name: ssl
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: ssl
          secret:
            secretName: {{ template "cloudify-services.name" . }}-certs
            optional: false

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
    {{- range .Values.nginx.port }}
    - name: {{ . | quote }}
      port: {{ . }}
    {{- end }}
  selector:
    app: nginx
  type: ClusterIP
