apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  containers:
    - image: docker.io/library/cloudify-manager-nginx
      imagePullPolicy: IfNotPresent
      name: nginx
      ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 53333
      resources: {}
      env:
        - name: REST_SERVICE_PORT
          value: "8100"
        - name: FILESERVER_PORT
          value: "9000"
      volumeMounts:
        - mountPath: /etc/cloudify/ssl
          name: ssl
          readOnly: true
  restartPolicy: Always
  volumes:
    - name: ssl
      persistentVolumeClaim:
        claimName: ssl
        readOnly: true

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
    - name: "80"
      port: 80
    - name: "443"
      port: 443
    - name: "53333"
      port: 53333
  selector:
    app: nginx
  type: NodePort
