apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: {{ .Values.nginx.image }}
          imagePullPolicy: {{ .Values.nginx.imagePullPolicy }}
          name: nginx
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 53333
          resources: {}
          volumeMounts:
            - mountPath: {{ .Values.resources.ssl }}
              name: ssl
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: ssl
          secret:
            secretName: {{ template "cloudify-services.name" . }}-certs
            optional: false

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
    - name: "80"
      port: 80
    - name: "443"
      port: 443
    - name: "53333"
      port: 53333
  selector:
    app: nginx
  type: ClusterIP
