apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgresql
  name: postgresql
spec:
  replicas: {{ .Values.postgresql.replicas }}
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.postgres_db }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.postgres_password }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.postgres_user }}
          image: {{ .Values.postgresql.image }}
          imagePullPolicy: {{ .Values.postgresql.imagePullPolicy }}
          name: postgresql
          ports:
            - containerPort: {{ .Values.postgresql.port }}
      restartPolicy: Always
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  ports:
    - port: {{ .Values.postgresql.port }}
  selector:
    app: postgresql
  type: ClusterIP
