apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgresql
  name: postgresql
spec:
  replicas: {{ .Values.postgresql.replicas }}
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
        cloudify-name: postgresql-14
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.postgres_db }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.postgres_password }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.postgres_user }}
          image: {{ .Values.postgresql.image }}
          imagePullPolicy: {{ .Values.postgresql.imagePullPolicy }}
          name: postgresql
          ports:
            - containerPort: {{ .Values.postgresql.port }}
          {{- if .Values.postgresql.probes.readiness.enabled }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.postgresql.port}}
            initialDelaySeconds: {{ .Values.postgresql.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.postgresql.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.postgresql.probes.readiness.timeoutSeconds }}
            successThreshold: {{ .Values.postgresql.probes.readiness.successThreshold }}
            failureThreshold: {{ .Values.postgresql.probes.readiness.failureThreshold }}
          {{- end }}
      restartPolicy: Always
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  ports:
    - port: {{ .Values.postgresql.port }}
  selector:
    app: postgresql
  type: ClusterIP
