apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgresql
  name: postgresql
spec:
  replicas: {{ .Values.postgresql.replicas }}
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: cloudify_db
            - name: POSTGRES_PASSWORD
              value: cloudify
            - name: POSTGRES_USER
              value: cloudify
          image: docker.io/library/postgres
          imagePullPolicy: IfNotPresent
          name: postgresql
          resources: {}
          ports:
            - containerPort: 5432
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  ports:
    - port: 5432
  selector:
    app: postgresql
  type: ClusterIP
