apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgresql
  name: postgresql
spec:
  replicas: {{ .Values.postgresql.replicas }}
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.env.POSTGRES_DB }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.env.POSTGRES_PASSWORD }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.env.POSTGRES_USER }}
          image: {{ .Values.postgresql.image }}
          imagePullPolicy: {{ .Values.postgresql.imagePullPolicy }}
          name: postgresql
          resources: {}
          ports:
            - containerPort: {{ .Values.postgresql.port }}
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  ports:
    - port: {{ .Values.postgresql.port }}
  selector:
    app: postgresql
  type: ClusterIP
