apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  replicas: {{ .Values.rabbitmq.replicas }}
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
        cloudify-name: cloudify-rabbitmq
    spec:
      containers:
        - image: {{ .Values.rabbitmq.image }}
          imagePullPolicy: {{ .Values.rabbitmq.imagePullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          name: rabbitmq
          ports:
            - containerPort: {{ .Values.rabbitmq.ssl_port }}
            - containerPort: {{ .Values.rabbitmq.management_port }}
            - containerPort: {{ .Values.rabbitmq.metrics_port }}
          volumeMounts:
            - mountPath: /etc/cloudify/ssl
              name: ssl
              readOnly: true
          {{- if .Values.rabbitmq.probes.liveness.enabled }}
          livenessProbe:
            # See https://www.rabbitmq.com/monitoring.html#health-checks
            exec:
              command:
                - sh
                - -c
                - |
                  rabbitmq-diagnostics -q ping && \
                  rabbitmq-diagnostics -q status && \
                  rabbitmq-diagnostics -q check_running && \
                  rabbitmq-diagnostics -q check_local_alarms && \
                  rabbitmq-diagnostics -q listeners && \
                  rabbitmq-diagnostics -q check_virtual_hosts
            initialDelaySeconds: {{ .Values.rabbitmq.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.rabbitmq.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.rabbitmq.probes.liveness.timeoutSeconds }}
            successThreshold: {{ .Values.rabbitmq.probes.liveness.successThreshold }}
            failureThreshold: {{ .Values.rabbitmq.probes.liveness.failureThreshold }}
          {{- end }}
          {{- if .Values.rabbitmq.probes.readiness.enabled }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.rabbitmq.ssl_port}}
            initialDelaySeconds: {{ .Values.rabbitmq.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.rabbitmq.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.rabbitmq.probes.readiness.timeoutSeconds }}
            successThreshold: {{ .Values.rabbitmq.probes.readiness.successThreshold }}
            failureThreshold: {{ .Values.rabbitmq.probes.readiness.failureThreshold }}
          {{- end }}
      restartPolicy: Always
      volumes:
        - name: ssl
          secret:
            secretName: {{ template "cloudify-services.name" . }}-certs
            optional: false
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - name: ssl
      port: {{ .Values.rabbitmq.ssl_port }}
    - name: management
      port: {{ .Values.rabbitmq.management_port }}
    - name: metrics
      port: {{ .Values.rabbitmq.metrics_port }}
  selector:
    app: rabbitmq
  type: ClusterIP
