apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  replicas: {{ .Values.rabbitmq.replicas }}
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - image: {{ .Values.rabbitmq.image }}
          imagePullPolicy: {{ .Values.rabbitmq.imagePullPolicy }}
          name: rabbitmq
          resources: {}
          ports:
            - containerPort: 15671
            - containerPort: 15692
            - containerPort: 5671
          volumeMounts:
            - mountPath: {{ .Values.resources.ssl }}
              name: ssl
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: ssl
          secret:
            secretName: {{ template "cloudify-services.name" . }}-certs
            optional: false

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - name: "5671"
      port: 5671
    - name: "15671"
      port: 15671
  selector:
    app: rabbitmq
  type: ClusterIP
