apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rest-service
  name: rest-service
spec:
  replicas: {{ .Values.rest_service.replicas }}
  selector:
    matchLabels:
      app: rest-service
  template:
    metadata:
      labels:
        app: rest-service
        cloudify-name: cloudify-restservice
    spec:
      initContainers:
        - name: rest-service-init
          image: {{ .Values.rest_service.image }}
          imagePullPolicy: {{ .Values.rest_service.imagePullPolicy }}
          command:
            - /usr/bin/env
            - -S
            - bash
            - -exuc
            - |
              /opt/rest-service/docker/prepare_secrets.sh
              python -m manager_rest.configure_manager --db-wait postgresql

              cd /opt/rest-service/migrations
              alembic upgrade head

              python -m manager_rest.configure_manager -c "{{ .Values.rest_service.configPath }}"
          volumeMounts:
            - mountPath: /etc/cloudify/ssl
              name: ssl
              readOnly: true
            - name: config
              mountPath: {{ .Values.rest_service.configPath }}
              subPath: config.yaml
              readOnly: true
        {{ if .Values.fileserver.install }}
        - name: fileserver-create-resources-bucket
          image: {{ .Values.fileserver.client_image }}
          imagePullPolicy: {{ .Values.rest_service.imagePullPolicy }}
          args: [mb, minio/resources, --ignore-existing]
          env:
            - name: MINIO_SERVER_HOST
              value: fileserver
            - name: MINIO_SERVER_ACCESS_KEY
              value: {{ .Values.fileserver.access_key }}
            - name: MINIO_SERVER_SECRET_KEY
              value: {{ .Values.fileserver.secret_key }}
        - name: fileserver-make-resources-public
          image: {{ .Values.fileserver.client_image }}
          imagePullPolicy: {{ .Values.rest_service.imagePullPolicy }}
          args: [anonymous, set, public, minio/resources]
          env:
            - name: MINIO_SERVER_HOST
              value: fileserver
            - name: MINIO_SERVER_ACCESS_KEY
              value: {{ .Values.fileserver.access_key }}
            - name: MINIO_SERVER_SECRET_KEY
              value: {{ .Values.fileserver.secret_key }}
        - name: local-agent-packages-fetch
          image: alpine/curl
          imagePullPolicy: {{ .Values.rest_service.imagePullPolicy }}
          args:
            - sh
            - -c
            - mkdir -p /tmp/packages/agents && {{ ( include "cloudify-services.curl-download" ( list "/tmp/packages/agents" .Values.resources.packages.agents ) ) }}
          volumeMounts:
            - mountPath: /tmp/packages
              name: packages
        - name: fileserver-upload-agent-packages
          image: {{ .Values.fileserver.client_image }}
          imagePullPolicy: {{ .Values.rest_service.imagePullPolicy }}
          args: [cp, --recursive, /tmp/packages/, minio/resources/packages/]
          env:
            - name: MINIO_SERVER_HOST
              value: fileserver
            - name: MINIO_SERVER_ACCESS_KEY
              value: {{ .Values.fileserver.access_key }}
            - name: MINIO_SERVER_SECRET_KEY
              value: {{ .Values.fileserver.secret_key }}
          volumeMounts:
            - mountPath: /tmp/packages
              name: packages
        {{ end }}
      containers:
        - name: rest-service
          image: {{ .Values.rest_service.image }}
          imagePullPolicy: {{ .Values.rest_service.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.rest_service.port }}
          {{- if .Values.rest_service.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              port: {{ .Values.rest_service.port}}
              path: /api/v3.1/ok
            initialDelaySeconds: {{ .Values.rest_service.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.rest_service.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.rest_service.probes.liveness.timeoutSeconds }}
            successThreshold: {{ .Values.rest_service.probes.liveness.successThreshold }}
            failureThreshold: {{ .Values.rest_service.probes.liveness.failureThreshold }}
          {{- end }}
      restartPolicy: Always
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      volumes:
        - name: ssl
          secret:
            secretName: {{ template "cloudify-services.name" . }}-certs
            optional: false
        - name: packages
          emptyDir:
            sizeLimit: 500Mi
        - name: config
          configMap:
            name: rest-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: rest-service
spec:
  ports:
    - port: {{ .Values.rest_service.port }}
  selector:
    app: rest-service
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rest-service-config
data:
  config.yaml: |
    {{ .Values.rest_service.config | toYaml | nindent 4 }}
