apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rest-service
  name: rest-service
spec:
  replicas: {{ .Values.rest_service.replicas }}
  selector:
    matchLabels:
      app: rest-service
  template:
    metadata:
      labels:
        app: rest-service
    spec:
      initContainers:
        - name: rest-service-init
          image: {{ .Values.rest_service.image }}
          imagePullPolicy: {{ .Values.rest_service.imagePullPolicy }}
          command:
            - /usr/bin/env
            - -S
            - bash
            - -exuc
            - |
              /opt/rest-service/docker/prepare_secrets.sh
              export CONFIG_FILE="${CONFIG_FILE_PATH:-/tmp/config.yaml}"
              if [ ! -e "${CONFIG_FILE}" ] ; then
                echo "
                manager:
                  hostname: cloudify-manager
                  private_ip: ${ENTRYPOINT}
                  file_server_type: s3
                " > "${CONFIG_FILE}"
              fi
              python -m manager_rest.configure_manager --db-wait postgresql
              cd /opt/rest-service/migrations
              alembic upgrade head
          env:
            - name: ENTRYPOINT
              value: localhost
        - name: fileserver-create-resources-bucket
          image: {{ .Values.fileserver.client_image }}
          imagePullPolicy: {{ .Values.rest_service.imagePullPolicy }}
          args:
            - mb
            - minio/resources
          env:
            - name: MINIO_SERVER_HOST
              value: fileserver
            - name: MINIO_SERVER_ACCESS_KEY
              value: admin
            - name: MINIO_SERVER_SECRET_KEY
              value: admin123
        - name: fileserver-make-resources-public
          image: {{ .Values.fileserver.client_image }}
          imagePullPolicy: {{ .Values.rest_service.imagePullPolicy }}
          args:
            - anonymous
            - set
            - public
            - minio/resources
          env:
            - name: MINIO_SERVER_HOST
              value: fileserver
            - name: MINIO_SERVER_ACCESS_KEY
              value: admin
            - name: MINIO_SERVER_SECRET_KEY
              value: admin123
      containers:
        - name: rest-service
          image: {{ .Values.rest_service.image }}
          imagePullPolicy: {{ .Values.rest_service.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.rest_service.port }}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: rest-service
spec:
  ports:
    - port: {{ .Values.rest_service.port }}
  selector:
    app: rest-service
  type: ClusterIP
