apiVersion: v1
kind: Pod
metadata:
  labels:
    app: rest-service
  name: rest-service
spec:
  containers:
    - image: docker.io/library/cloudify-manager-rest_service
      imagePullPolicy: IfNotPresent
      name: rest-service
      resources: {}
      ports:
        - containerPort: 8100
      volumeMounts:
        - mountPath: /opt/manager
          name: manager-config
  restartPolicy: Always
  volumes:
    - name: manager-config
      persistentVolumeClaim:
        claimName: manager-config

---
apiVersion: v1
kind: Service
metadata:
  name: rest-service
spec:
  ports:
    - port: 8100
  selector:
    app: rest-service
  type: NodePort
