apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rest-service
  name: rest-service
spec:
  replicas: {{ .Values.rest_service.replicas }}
  selector:
    matchLabels:
      app: rest-service
  template:
    metadata:
      labels:
        app: rest-service
    spec:
      initContainers:
        - name: rest-service-init
          image: {{ .Values.rest_service.image }}
          imagePullPolicy: {{ .Values.rest_service.imagePullPolicy }}
          command:
            - /usr/bin/env
            - -S
            - bash
            - -exuc
            - |
              /opt/rest-service/docker/prepare_secrets.sh
              export CONFIG_FILE="${CONFIG_FILE_PATH:-/tmp/config.yaml}"
              if [ ! -e "${CONFIG_FILE}" ] ; then
                echo "
                manager:
                  hostname: cloudify-manager
                  private_ip: ${ENTRYPOINT}
                " > "${CONFIG_FILE}"
              fi
              python -m manager_rest.configure_manager --db-wait postgresql
              cd /opt/rest-service/migrations
              alembic upgrade head
          env:
            - name: ENTRYPOINT
              value: localhost
          volumeMounts:
            - mountPath: /opt/manager
              name: manager-volume
      containers:
        - name: rest-service
          image: {{ .Values.rest_service.image }}
          imagePullPolicy: {{ .Values.rest_service.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.rest_service.port }}
          volumeMounts:
            - mountPath: /opt/manager
              name: manager-volume
      restartPolicy: Always
      volumes:
        - name: manager-volume
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: rest-service
spec:
  ports:
    - port: {{ .Values.rest_service.port }}
  selector:
    app: rest-service
  type: ClusterIP
