apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stage-backend
  name: stage-backend
spec:
  replicas: {{ .Values.stage_backend.replicas }}
  selector:
    matchLabels:
      app: stage-backend
  template:
    metadata:
      labels:
        app: stage-backend
    spec:
      containers:
        - env:
            - name: RESTSERVICE_ADDRESS
              value: {{ .Values.stage_backend.restservice_address }}
          image: {{ .Values.stage_backend.image }}
          imagePullPolicy: {{ .Values.stage_backend.imagePullPolicy }}
          name: stage-backend
          ports:
            - containerPort: {{ .Values.stage_backend.port }}
          volumeMounts:
            - mountPath: /etc/cloudify/ssl
              name: ssl
              readOnly: true
          {{- if .Values.stage_backend.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              port: {{ .Values.stage_backend.port }}
              path: "/config/"
            initialDelaySeconds: {{ .Values.stage_backend.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.stage_backend.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.stage_backend.probes.liveness.timeoutSeconds }}
            successThreshold: {{ .Values.stage_backend.probes.liveness.successThreshold }}
            failureThreshold: {{ .Values.stage_backend.probes.liveness.failureThreshold }}
          {{- end }}
      restartPolicy: Always
      volumes:
        - name: ssl
          secret:
            secretName: {{ template "cloudify-services.name" . }}-certs
            optional: false
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: stage-backend
spec:
  ports:
    - port: {{ .Values.stage_backend.port }}
  selector:
    app: stage-backend
  type: ClusterIP
