apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stage-frontend
  name: stage-frontend
spec:
  replicas: {{ .Values.stage_frontend.replicas }}
  selector:
    matchLabels:
      app: stage-frontend
  template:
    metadata:
      labels:
        app: stage-frontend
    spec:
      containers:
        - image: {{ .Values.stage_frontend.image }}
          imagePullPolicy: {{ .Values.stage_frontend.imagePullPolicy }}
          name: stage-frontend
          resources: {}
          ports:
            - containerPort: {{ .Values.stage_frontend.port }}
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: stage-frontend
spec:
  ports:
    - port: {{ .Values.stage_frontend.port }}
  selector:
    app: stage-frontend
  type: ClusterIP
