apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stage-frontend
  name: stage-frontend
spec:
  replicas: {{ .Values.stage_frontend.replicas }}
  selector:
    matchLabels:
      app: stage-frontend
  template:
    metadata:
      labels:
        app: stage-frontend
    spec:
      containers:
        - image: docker.io/library/stage_frontend
          imagePullPolicy: IfNotPresent
          name: stage-frontend
          resources: {}
          ports:
            - containerPort: 8188
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: stage-frontend
spec:
  ports:
    - port: 8188
  selector:
    app: stage-frontend
  type: ClusterIP
