apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stage-backend
  name: stage-backend
spec:
  replicas: {{ .Values.stage_backend.replicas }}
  selector:
    matchLabels:
      app: stage-backend
  template:
    metadata:
      labels:
        app: stage-backend
    spec:
      containers:
        - env:
            - name: RESTSERVICE_ADDRESS
              value: nginx
          image: docker.io/library/stage_backend
          imagePullPolicy: IfNotPresent
          name: stage-backend
          resources: {}
          ports:
            - containerPort: 8088
          volumeMounts:
            - mountPath: /etc/cloudify/ssl
              name: ssl
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: ssl
          secret:
            secretName: {{ template "cloudify-services.name" . }}-certs
            optional: false

---
apiVersion: v1
kind: Service
metadata:
  name: stage-backend
spec:
  ports:
    - port: 8088
  selector:
    app: stage-backend
  type: ClusterIP
