apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stage-frontend
  name: stage-frontend
spec:
  replicas: {{ .Values.stage_frontend.replicas }}
  selector:
    matchLabels:
      app: stage-frontend
  template:
    metadata:
      labels:
        app: stage-frontend
        cloudify-name: stage-frontend
    spec:
      containers:
        - image: {{ .Values.stage_frontend.image }}
          imagePullPolicy: {{ .Values.stage_frontend.imagePullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          name: stage-frontend
          ports:
            - containerPort: {{ .Values.stage_frontend.port }}
          {{- if .Values.stage_frontend.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              port: {{ .Values.stage_frontend.port}}
              path: "/static/"
            initialDelaySeconds: {{ .Values.stage_frontend.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.stage_frontend.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.stage_frontend.probes.liveness.timeoutSeconds }}
            successThreshold: {{ .Values.stage_frontend.probes.liveness.successThreshold }}
            failureThreshold: {{ .Values.stage_frontend.probes.liveness.failureThreshold }}
          {{- end }}
      restartPolicy: Always
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: stage-frontend
spec:
  ports:
    - port: {{ .Values.stage_frontend.port }}
  selector:
    app: stage-frontend
  type: ClusterIP
