apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudify-manager-aio.name" . }}
  labels:
    name: {{ template "cloudify-manager-aio.name" . }}
{{ include "cloudify-manager-aio.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "cloudify-manager-aio.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "cloudify-manager-aio.name" . }}
    spec:
      containers:
      - name: {{ template "cloudify-manager-aio.name" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          httpGet:
            path: {{ .Values.readinessProbe.path }}
            port: {{ .Values.readinessProbe.port }}
        {{- end}}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        volumeMounts:
        - mountPath: /run
          name: run
        - mountPath: /run/lock
          name: runlock
      volumes:
      - name: run
        emptyDir:
          medium: Memory
          sizeLimit: "2Gi"
      - name: runlock
        emptyDir:
          medium: Memory
          sizeLimit: "2Gi"
    {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
    {{- end }}
